// Base real do estudo de concorrência do Synthè (Plaenge · TGD, Mont'Serrat,
// Porto Alegre). Nenhum dado aqui é fictício — vem da pasta de pesquisa
// "concorrentes synthe" (tabelas de vendas, memoriais descritivos, books),
// do Órulo (consulta autenticada em 25/ago/2026) e de checagem cruzada com
// Rial Imóveis + sites institucionais das incorporadoras.
//
// Ver SOURCES para a legenda de cada chave usada em `fontes`.

export const SOURCES = {
  tabela: {
    label: 'Tabela de vendas oficial',
    detalhe: 'Preço/m² por unidade em estoque, mar/2026 (concorrentes) e ago/2026 (Synthè)',
  },
  orulo: {
    label: 'Órulo',
    detalhe: 'Plataforma paga, sessão autenticada — estoque, lançamento/entrega, áreas comuns, preço "a partir". Consultado em 25/ago/2026',
  },
  rial: {
    label: 'Rial Imóveis',
    detalhe: '211 anúncios ativos na região cruzados por preço/m² — validação independente, 25/ago/2026',
  },
  memorial: {
    label: 'Memorial / ficha técnica / book',
    detalhe: 'PDFs oficiais das incorporadoras — estrutura, fachada, esquadrias, equipe de projeto',
  },
  web: {
    label: 'Site institucional / busca dirigida',
    detalhe: 'Sites das incorporadoras e portais (Bridge, Colnaghi, Foxter, Auxiliadora Predial, Urban) — confirmação cruzada de incorporadora, datas e resolução de divergências',
  },
}

const AMENITY_KEYS = [
  ['salaoFestas', 'Salão de festas'],
  ['sGourmet', 'Espaço gourmet'],
  ['brinquedoteca', 'Brinquedoteca'],
  ['playground', 'Playground'],
  ['quadraPoli', 'Quadra poliesportiva'],
  ['academia', 'Academia'],
  ['saunaSeca', 'Sauna seca'],
  ['saunaUmida', 'Sauna úmida'],
  ['salaMassagem', 'Sala de massagem'],
  ['piscinaInterna', 'Piscina interna'],
  ['piscinaExterna', 'Piscina externa'],
  ['espacoPet', 'Espaço pet'],
  ['bicicletario', 'Bicicletário'],
  ['quadraTenis', 'Quadra de tênis'],
  ['quadraBeachTenis', 'Quadra de beach tênis'],
]
export { AMENITY_KEYS }

function amenCount(amen) {
  return AMENITY_KEYS.reduce((n, [k]) => n + (amen[k] === true ? 1 : 0), 0)
}

const raw = [
  {
    id: 'synthe',
    isSynthe: true,
    nome: 'Synthè',
    incorporadora: 'Plaenge · TGD (PL POA 02 Empreendimentos Imobiliários Ltda.)',
    bairro: "Mont'Serrat",
    endereco: 'Rua Pedro Ivo, 542/554/564',
    dataLancamento: '2026-03-20',
    dataLancamentoObs: 'confirmado — registro de incorporação R.1/222.853',
    dataEntrega: null,
    totalUnidades: 32,
    unidadesEstoque: 19,
    tipologia: '3 suítes (1 master + 2 comuns)',
    metragem: '171,57 – 180,39 m² (tipo) · 295,99 – 298,94 m² (cobertura duplex)',
    precoM2: 18507,
    precoAPartirOrulo: null,
    pavimentos: 20,
    aptosPorAndar: 2,
    projeto: 'Baldasso Arquitetura e Engenharia (Arq. Francisco Majewski · Eng. Daniel Mendes de Leão)',
    interiores: 'Maena Design Conecta',
    paisagismo: 'Creare Paisagismo',
    luminotecnico: 'Maena Design Conecta',
    gerador: 'Pleno (100% dos apartamentos + infra condominial prioritária)',
    amenidades: {
      salaoFestas: true, sGourmet: 'parcial', brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: true, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Concreto armado convencional, lajes maciças de 14cm; fachadas e divisões interapartamento em bloco cerâmico com reboco; divisórias internas em drywall; manta acústica sob contrapiso em dormitórios e estar (NBR 15575).',
    esquadrias: 'Dormitórios em alumínio anodizado ou PVC de correr, com persianas de enrolar integradas de fábrica (manual); living em porta-janela de correr piso-teto em alumínio ou PVC. Entrega "no osso": contrapiso cimentado 5cm, laje aparente c/ pintura em suítes e living, sem tampos/louças/metais.',
    outros: 'Certificação Diamante de Sustentabilidade Ambiental; placas fotovoltaicas (≥30% da demanda de iluminação das áreas comuns); LED 100% nas áreas condominiais; 72 boxes privativos + carregador elétrico em ≥1 box/unidade; reconhecimento facial nos elevadores sociais + guarita com vidro blindado; Honesty Market (minimercado autônomo).',
    observacao: 'Memorial completo chegou depois da nossa primeira rodada de pesquisa — antes o Synthè era o único da base sem specs públicas, agora tem uma das fichas mais detalhadas do grupo (inclusive custo de construção: R$31,87 milhões, R$3.635–3.640/m²). Compartilha a Certificação Diamante de Sustentabilidade com Marquês 650 e Matiz Moinhos, e o reconhecimento facial nos elevadores com o Ubá.',
    fontes: ['tabela', 'memorial'],
  },
  {
    id: 'uba',
    nome: 'Ubá',
    incorporadora: 'Zuckhan',
    bairro: 'Bela Vista',
    endereco: 'Rua Barão de Ubá, 690',
    dataLancamento: '2025-09-01',
    dataEntrega: '2028-09-30',
    totalUnidades: 32,
    unidadesEstoque: 17,
    tipologia: '3 suítes',
    metragem: '178 – 331 m²',
    precoM2: 18551,
    precoAPartirOrulo: 4165730,
    pavimentos: 19,
    aptosPorAndar: 2,
    projeto: 'Torres Arquiteto',
    interiores: 'Arquitetura Nacional',
    paisagismo: 'Recanto Paisagismo',
    luminotecnico: 'Cristina Maluf',
    gerador: '100%',
    amenidades: {
      salaoFestas: true, sGourmet: false, brinquedoteca: true, playground: true,
      quadraPoli: true, academia: true, saunaSeca: true, saunaUmida: false,
      salaMassagem: true, piscinaInterna: true, piscinaExterna: true,
      espacoPet: false, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Fachada em painel arquitetônico premium.',
    esquadrias: 'Esquadrias piso-teto com vidro duplo.',
    outros: 'Segurança com biometria/reconhecimento facial; automação residencial (iluminação, som, cortinas); adega climatizada privativa por apto; elevador panorâmico; pé-direito de 3m.',
    observacao: 'Corrigido nesta pesquisa: incorporadora é Zuckhan, não Woss (base de março) — confirmado por 3 fontes independentes (Órulo, site oficial da Zuckhan, portais).',
    fontes: ['tabela', 'orulo', 'memorial', 'web'],
  },
  {
    id: 'bordini',
    nome: 'Bordini 1595',
    incorporadora: 'Tomasetto',
    bairro: 'Bela Vista',
    endereco: 'Rua Coronel Bordini, 1595',
    dataLancamento: '2024-04-01',
    dataEntrega: '2027-04-30',
    totalUnidades: 23,
    unidadesEstoque: 3,
    tipologia: '3 suítes',
    metragem: '154 – 198 m² (+ 2 coberturas duplex)',
    precoM2: 24666,
    precoAPartirOrulo: 2868900,
    pavimentos: 14,
    aptosPorAndar: 2,
    projeto: 'Ronaldo Rezende',
    interiores: null,
    paisagismo: 'Tellini Vontobel',
    luminotecnico: null,
    gerador: 'Full',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: true, saunaUmida: false,
      salaMassagem: true, piscinaInterna: true, piscinaExterna: false,
      espacoPet: false, bicicletario: false, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'nenhum',
    estrutura: 'Não informado — sem memorial descritivo disponível, apenas book institucional.',
    esquadrias: 'Não informado.',
    outros: 'Fitness de 86m² assinado por Lucas Pretto (Pretto Treinamento).',
    observacao: 'Maior velocidade de venda da base (87%) mesmo sendo o mais caro por m² — marca/produto pesam mais que preço aqui.',
    fontes: ['tabela', 'orulo', 'rial'],
  },
  {
    id: 'artur-rocha',
    nome: 'Artur Rocha 1133',
    incorporadora: 'AB Incorporadora',
    bairro: 'Bela Vista',
    endereco: 'Rua Artur Rocha, 1133',
    dataLancamento: '2023-11-01',
    dataEntrega: '2027-11-30',
    totalUnidades: 10,
    unidadesEstoque: 6,
    tipologia: '3 suítes',
    metragem: '180 – 229 m² (garden)',
    precoM2: 22012,
    precoAPartirOrulo: 4990000,
    pavimentos: 12,
    aptosPorAndar: 1,
    projeto: 'Hype Studio',
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Full',
    amenidades: {
      salaoFestas: true, sGourmet: false, brinquedoteca: false, playground: false,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: false,
      espacoPet: false, bicicletario: false, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Não informado.',
    esquadrias: 'Esquadrias piso-teto.',
    outros: 'Espera p/ carregador elétrico (1/apto); isolamento acústico nas tubulações; manta acústica entre laje e contrapiso; persiana motorizada.',
    observacao: 'Preço/m² (R$22.011 no Órulo) bate quase exato com nosso cálculo próprio (R$22.012) — boa validação cruzada.',
    fontes: ['tabela', 'orulo', 'memorial', 'web'],
  },
  {
    id: 'galeria-jardim',
    nome: 'Galeria Jardim',
    incorporadora: 'Woss',
    bairro: "Mont'Serrat",
    endereco: 'Rua Silva Jardim, 600',
    dataLancamento: '2026-05-07',
    dataEntrega: '2029-07-31',
    totalUnidades: 54,
    unidadesEstoque: 28,
    tipologia: '3 suítes',
    metragem: '154,62 – 352,20 m² (tipo, garden e cobertura)',
    precoM2: null,
    precoAPartirOrulo: 2172287,
    pavimentos: 18,
    aptosPorAndar: 4,
    projeto: 'Studio Ronaldo Rezende',
    interiores: 'Vitá Arquitetos',
    paisagismo: 'Tellini Vontobel',
    luminotecnico: 'Studio Sandra Thomé',
    gerador: 'Full',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: true, academia: true, saunaSeca: true, saunaUmida: true,
      salaMassagem: true, piscinaInterna: true, piscinaExterna: true,
      espacoPet: true, bicicletario: true, quadraTenis: false, quadraBeachTenis: true,
    },
    profundidade: 'completo',
    estrutura: 'Altura de pavimento 3,05m; laje + manta acústica de alto desempenho + contrapiso, piso com 19 a 24cm — atenuação acústica.',
    esquadrias: 'Esquadrias piso-teto com peitoril em vidro; alumínio anodizado de alto desempenho; vidros laminados termoacústicos; persianas motorizadas nas suítes.',
    outros: 'Água quente individual; churrasqueira c/ exaustão mecânica; lareira a lenha; espera adega (projeto Lacava); guarita com vidros multilaminados.',
    observacao: 'Divergência resolvida: ficha técnica oficial confirma 54 unidades (não 72, número que nunca existiu de fato nas fontes — era artefato de busca). Vendeu 26 das 54 desde o lançamento em mai/2026.',
    fontes: ['orulo', 'memorial', 'web'],
  },
  {
    id: 'marques-650',
    nome: 'Marquês 650',
    incorporadora: 'Woss',
    bairro: 'Moinhos de Vento',
    endereco: 'Rua Marquês do Herval, 650',
    dataLancamento: '2025-05-30',
    dataEntrega: '2028-03-30',
    totalUnidades: 47,
    unidadesEstoque: 29,
    tipologia: '3 e 4 suítes',
    metragem: '143,76 – 330,43 m² (incl. coberturas duplex)',
    precoM2: 18810,
    precoAPartirOrulo: 2552400,
    pavimentos: 15,
    aptosPorAndar: 4,
    projeto: 'OPSA (+ restauração: arq. Evandro Eifler Jr.)',
    interiores: 'OPSA',
    paisagismo: 'Tellini Vontobel',
    luminotecnico: 'OPSA',
    gerador: 'Full',
    amenidades: {
      salaoFestas: true, sGourmet: false, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: true,
      salaMassagem: true, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Restauração de prédio histórico (Patrimônio Histórico, arq. Evandro Eifler Jr.); abas e sacadas em concreto aparente — sombreamento + compartimentação de incêndio.',
    esquadrias: 'Esquadrias piso-teto com trilhos embutidos; alumínio anodizado de alto desempenho; vidros laminados termoacústicos; persianas motorizadas.',
    outros: 'Pisos em Pedra Portuguesa; revestimentos nobres (mármore Donatello e amadeirados); piscina raia 25m; Selo Diamante de Sustentabilidade.',
    observacao: 'Único projeto de restauração de prédio histórico da base — história impossível de replicar pelos concorrentes.',
    fontes: ['tabela', 'orulo', 'memorial', 'web'],
  },
  {
    id: 'nuances',
    nome: 'Nuances',
    incorporadora: 'Ivo Rizzo',
    bairro: 'Moinhos de Vento',
    endereco: 'Rua Coronel Bordini, 668',
    dataLancamento: '2025-08-27',
    dataEntrega: '2028-12-31',
    totalUnidades: 17,
    unidadesEstoque: 13,
    tipologia: '3 suítes',
    metragem: '154 – 326 m² (4 tipologias, incl. cobertura)',
    precoM2: 19521,
    precoAPartirOrulo: 3025265,
    pavimentos: 12,
    aptosPorAndar: 2,
    projeto: 'Smart Arquitetura (desenv.: Cimo Arquitetura)',
    interiores: 'Ar Arquitetura',
    paisagismo: 'Daniel Dillenburg',
    luminotecnico: null,
    gerador: 'Sim',
    amenidades: {
      salaoFestas: true, sGourmet: false, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Concreto armado convencional; alvenaria em bloco cerâmico 19cm com isolamento acústico; fachada em revestimento cerâmico Eliane (Chelsea Powder Mesh) + amadeirado HPL/ACM; peitoris em basalto polido.',
    esquadrias: 'Alumínio c/ pintura eletrostática branca ou PVC branco, vidro laminado; vidro duplo insulado nos dormitórios; persianas motorizadas.',
    outros: 'Toldos de fachada motorizados; Selo Diamante de Sustentabilidade.',
    observacao: null,
    fontes: ['tabela', 'orulo', 'memorial', 'web'],
  },
  {
    id: 'legacy',
    nome: 'Legacy · Porsche Consulting',
    incorporadora: 'Cyrela Goldsztein',
    bairro: 'Moinhos de Vento',
    endereco: 'Rua Dr. Florêncio Ygartua, 415',
    dataLancamento: '2025-08-06',
    dataEntrega: '2028-10-31',
    totalUnidades: 48,
    unidadesEstoque: 18,
    tipologia: '3 e 4 suítes',
    metragem: '168 – 393 m² (incl. coberturas duplex)',
    precoM2: 20798,
    precoAPartirOrulo: 3529292,
    pavimentos: 16,
    aptosPorAndar: 4,
    projeto: 'Hype Studio',
    interiores: 'Cassia Kroeff',
    paisagismo: 'Creare',
    luminotecnico: null,
    gerador: 'N/S',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: true, academia: true, saunaSeca: true, saunaUmida: null,
      salaMassagem: null, piscinaInterna: true, piscinaExterna: true,
      espacoPet: true, bicicletario: true, quadraTenis: true, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Torre de 16 pavimentos, 48 aptos (4/andar); paredes em alvenaria; fachadas em revestimento texturizado e/ou pintura — sem revestimento nobre/pétreo.',
    esquadrias: 'Alumínio com guarnições em alumínio, acabamento em pintura (padrão Cyrela); não entregues em ambientes de serviço.',
    outros: '3 elevadores (2 sociais + 1 serviço), marca Atlas.',
    observacao: 'Apesar da marca "Porsche Consulting", a especificação de fachada é mais simples que a de outros concorrentes do mesmo padrão de preço.',
    fontes: ['tabela', 'orulo', 'memorial', 'web'],
  },
  {
    id: 'anita-green',
    nome: 'Anita Green',
    incorporadora: 'Joal Teitelbaum',
    bairro: "Mont'Serrat",
    endereco: 'Rua Anita Garibaldi, 51',
    dataLancamento: '2021-04-01',
    dataEntrega: '2025-09-30',
    totalUnidades: 37,
    unidadesEstoque: 8,
    tipologia: '3 suítes (+ 2 dorm. e garden)',
    metragem: '155,76 – 192,60 m² (+ 75,68 m² e garden 361,54 m²)',
    precoM2: 19865,
    precoAPartirOrulo: 3604355,
    pavimentos: 16,
    aptosPorAndar: 2,
    projeto: 'Ideia1 Arquitetura',
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Sim',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: true, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: null, bicicletario: null, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Fachadas em painel arquitetônico.',
    esquadrias: 'Vidros duplos nos dormitórios.',
    outros: 'Iluminação automatizada nos apartamentos; gerador conforme carga definida em projeto.',
    observacao: 'Corrigido nesta pesquisa: total real é 37 unidades (não 24 — a tabela de março só listava o que ainda estava à venda). Único concorrente no mesmo bairro do Synthè com preço de tabela ativo.',
    fontes: ['tabela', 'orulo', 'rial', 'memorial'],
  },
  {
    id: 'matiz-moinhos',
    nome: 'Matiz Moinhos',
    incorporadora: 'Zuckhan',
    bairro: 'Auxiliadora',
    endereco: 'Rua Coronel Bordini, 1024',
    dataLancamento: '2024-10-17',
    dataEntrega: '2029-09-30',
    totalUnidades: 28,
    unidadesEstoque: 19,
    tipologia: '3 suítes',
    metragem: '153 – 254 m² (incl. garden e cobertura)',
    precoM2: 18276,
    precoAPartirOrulo: 2567158,
    pavimentos: 17,
    aptosPorAndar: 2,
    projeto: 'Não identificado (só logo no material)',
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: '100%',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: true,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: null, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Concreto aparente tratado; plaquetas cerâmicas na fachada.',
    esquadrias: 'Alumínio com pintura eletrostática e vidros laminados.',
    outros: 'Certificação de Sustentabilidade Ambiental Diamante; LED 100% nas áreas condominiais; infra p/ carregador elétrico; guarita com vidros blindados.',
    observacao: 'Data de entrega divergia entre portais (out/2027 a set/2028) — resolvido com a data oficial do Órulo (set/2029).',
    fontes: ['tabela', 'orulo', 'memorial'],
  },
  {
    id: 'aura',
    nome: 'Aura',
    incorporadora: 'Frass',
    bairro: 'Bela Vista',
    endereco: 'Rua Coronel Bordini, 1644',
    dataLancamento: '2021-11-01',
    dataEntrega: '2025-03-30',
    totalUnidades: 23,
    unidadesEstoque: 3,
    tipologia: '3 suítes',
    metragem: '160,52 – 187,62 m² (garden 288,90 m²)',
    precoM2: 21073,
    precoAPartirOrulo: 3659369,
    pavimentos: 13,
    aptosPorAndar: 2,
    projeto: 'André Petracco Arquitetura e Smart',
    interiores: 'Ambidestro Arquitetura',
    paisagismo: 'Krebs+ Paisagismo',
    luminotecnico: 'Stúdio FOS Iluminação',
    gerador: 'Sim',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: false,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: null, bicicletario: null, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Concreto armado convencional; alvenaria em bloco cerâmico; fachada em concreto aparente e porcelanato imitando madeira; brises em alumínio e ACM pintado no térreo.',
    esquadrias: 'PVC ou alumínio c/ pintura eletrostática cor chumbo, vidro laminado; esquadrias internas em madeira maciça branca; persianas automatizadas nas suítes.',
    outros: 'Piscina com pastilhas NGK/Atlas; adega condominial climatizada (Lacava).',
    observacao: 'Entregue desde mar/2025 — "Pronto novo". Empata com Bordini 1595 como o mais vendido da base (87%).',
    fontes: ['tabela', 'orulo', 'rial', 'memorial'],
  },
  {
    id: 'casa-gardel',
    nome: 'Casa Gardel',
    incorporadora: 'PlatzPar (constr. 4T Construtora)',
    bairro: 'Bela Vista',
    endereco: 'Rua Carlos Gardel, 210',
    dataLancamento: '2026-03-01',
    dataEntrega: '2029-03-31',
    totalUnidades: 13,
    unidadesEstoque: 9,
    tipologia: '3 suítes (+ garden e andar inteiro)',
    metragem: '117 – 255 m² (garden 173,28 m²)',
    precoM2: 18042,
    precoAPartirOrulo: 2001757,
    pavimentos: 10,
    aptosPorAndar: 2,
    projeto: 'Não identificado no material',
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Pleno',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: null, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Torre única em concreto aparente (design autoral valoriza biofilia + concreto aparente).',
    esquadrias: 'Vidros duplos em todos os apartamentos.',
    outros: 'Churrasqueira em todos os apartamentos; estacionamento com pintura epóxi; certificado de Sustentabilidade Ambiental (redução de IPTU).',
    observacao: 'Incorporadora só identificada via busca web (PlatzPar) — não aparece nos PDFs de vendas.',
    fontes: ['tabela', 'orulo', 'web'],
  },
  {
    id: 'artisan',
    nome: 'Artisan',
    incorporadora: 'Adolfo Starosta Construções e Incorporações',
    bairro: 'Auxiliadora',
    endereco: 'Rua Felipe Neri, 110',
    dataLancamento: '2023-09-19',
    dataLancamentoObs: 'data do registro de incorporação',
    dataEntrega: '2026-05-31',
    totalUnidades: 26,
    unidadesEstoque: 8,
    tipologia: '3 suítes',
    metragem: '151,47 – 173,37 m² (garden)',
    precoM2: 15788,
    precoAPartirOrulo: null,
    pavimentos: 15,
    aptosPorAndar: 2,
    projeto: 'Joaquim Haas e Jorge D. de Jesus Arquitetos Associados',
    interiores: 'Cassia Kroeff Estúdio de Arquitetura (áreas comuns)',
    paisagismo: 'Fernando Thunm Paisagismo',
    luminotecnico: null,
    gerador: 'Parcial (áreas comuns, acesso e elevadores — não atende apartamentos)',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: false,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: true, bicicletario: true, quadraTenis: false, quadraBeachTenis: true,
    },
    profundidade: 'completo',
    estrutura: 'Concreto armado convencional; paredes em bloco cerâmico 11,5/14/19cm; fachada em granito + plaquetas/pastilhas (linhas NGK, Gail, Atlas).',
    esquadrias: 'Alumínio anodizado cor bronze; vidros laminados nas sacadas.',
    outros: 'Gerador a diesel (áreas comuns); 2 elevadores (Atlas-Schindler/ThyssenKrupp/Otis); coworking com sala de reuniões; fechadura Yale/Papaiz; sistema PPCI Casa dos Extintores.',
    observacao: 'Novo concorrente localizado nesta rodada de pesquisa (não estava na base original de 11). Sem cobertura Órulo/Rial ainda — dados vêm do book/memorial local + confirmação web da incorporadora.',
    fontes: ['tabela', 'memorial', 'web'],
  },
  {
    id: 'roca-815',
    nome: 'Roca 815',
    incorporadora: 'AMX Property + Mapa Incorporadora',
    bairro: 'Bela Vista',
    endereco: 'Rua Artur Rocha, 815',
    dataLancamento: null,
    dataEntrega: '2027-12-31',
    totalUnidades: 11,
    unidadesEstoque: 6,
    tipologia: '3 suítes (opção de 4ª suíte)',
    metragem: '203,56 – 251,38 m² (garden)',
    precoM2: 20728,
    precoAPartirOrulo: null,
    pavimentos: 12,
    aptosPorAndar: 1,
    projeto: 'Arq. Maria Eduarda "Duda" Kopper',
    interiores: 'Butiá Arquitetura',
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Full',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: false,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Laje maciça de 20cm + contrapiso; paredes externas duplas nos dormitórios; fachada em plaquetas + pedra natural.',
    esquadrias: 'Amplas, com fecho tipo cremona; vidros laminados.',
    outros: 'Certificação Diamante de Sustentabilidade; fechadura eletrônica; piso aquecido nos banheiros; espera para carregador elétrico (1/apto); piscina no rooftop; tubulação PPR com atenuação acústica de esgoto.',
    observacao: 'Novo concorrente localizado nesta rodada. Só 11 unidades (1/andar) — menor densidade da base depois do Synthè. Registro de incorporação sem data legível no material disponível.',
    fontes: ['tabela', 'memorial', 'web'],
  },
  {
    id: 'seen-boa-vista',
    nome: 'SEEN Boa Vista',
    incorporadora: 'Melnick',
    bairro: 'Boa Vista',
    endereco: 'Rua Anita Garibaldi',
    dataLancamento: '2021-07-01',
    dataLancamentoObs: 'fonte: site institucional/portais — não confirmado em PDF primário',
    dataEntrega: '2024-05-31',
    totalUnidades: 64,
    unidadesEstoque: 3,
    tipologia: '3 suítes (+ duplex)',
    metragem: '156,44 – 308,20 m² (duplex)',
    precoM2: 17585,
    precoAPartirOrulo: null,
    pavimentos: 17,
    aptosPorAndar: null,
    projeto: null,
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: null,
    amenidades: {
      salaoFestas: null, sGourmet: null, brinquedoteca: null, playground: null,
      quadraPoli: null, academia: null, saunaSeca: null, saunaUmida: null,
      salaMassagem: null, piscinaInterna: null, piscinaExterna: null,
      espacoPet: null, bicicletario: null, quadraTenis: true, quadraBeachTenis: null,
    },
    profundidade: 'nenhum',
    estrutura: 'Não informado — sem memorial local, apenas tabela de vendas.',
    esquadrias: 'Não informado.',
    outros: 'Mais de 2.000 m² de área de lazer, incluindo quadra de tênis de saibro (diferencial raro na região).',
    observacao: 'Bairro fora do cluster central da pesquisa (Boa Vista, não Bela Vista/Moinhos/Auxiliadora/Mont\'Serrat) — geograficamente mais distante do Synthè, incluído por faixa de preço. Já entregue (mai/2026), quase esgotado (95,3% vendido) — total de 64 unidades confirmado por busca web direcionada (melnick.com.br), resolvendo a ausência de ficha técnica numérica no book local.',
    fontes: ['tabela', 'web'],
  },
  {
    id: 'seen-tres-figueiras',
    nome: 'SEEN Três Figueiras',
    incorporadora: 'Melnick',
    bairro: 'Três Figueiras',
    endereco: 'Alameda Eduardo Guimarães, 101',
    dataLancamento: '2025-09-01',
    dataLancamentoObs: 'fonte web, não confirmado em PDF primário',
    dataEntrega: '2029-04-30',
    dataEntregaObs: 'fonte web, não confirmado em PDF primário',
    totalUnidades: null,
    totalUnidadesObs: 'Fontes divergem: buscas web citam tanto "72 unidades" (18 pavimentos × 4/andar) quanto "62 unidades" (torre de 19 pavimentos) — mesmo padrão de conta "andares × unidades/andar" que já se mostrou um artefato de busca no caso do Galeria Jardim. Sem ficha técnica numérica encontrada no book local (empreendimento em pré-lançamento, memorial de incorporação ainda não registrado). Não usamos nem 72 nem 62 sem confirmação em fonte primária.',
    unidadesEstoque: 35,
    unidadesEstoqueObs: 'unidades com preço na tabela de vendas, mar/2026 — pode não representar o estoque total atual',
    tipologia: '3 e 4 suítes',
    metragem: '149,90 – 299,27 m²',
    precoM2: 18342,
    precoAPartirOrulo: null,
    pavimentos: null,
    pavimentosObs: 'fontes web divergem entre 18 e 19 pavimentos',
    aptosPorAndar: null,
    projeto: null,
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Pontual (áreas comuns + pontos específicos, não 100% dos apartamentos)',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: true, academia: true, saunaSeca: true, saunaUmida: false,
      salaMassagem: false, piscinaInterna: true, piscinaExterna: true,
      espacoPet: true, bicicletario: false, quadraTenis: false, quadraBeachTenis: true,
    },
    profundidade: 'completo',
    estrutura: 'Não detalhado no book disponível (foco do material é lazer/planta, não estrutura).',
    esquadrias: 'Não detalhado no book disponível.',
    outros: 'Reconhecimento facial; recirculação de água quente; piscina coberta recreativa com raia de 20m; mini-market; storage; miniquadra; espaço gourmet externo.',
    observacao: 'MAIOR LACUNA DA BASE: total de unidades não confirmado (ver totalUnidadesObs) — empreendimento em pré-lançamento, ainda sem registro de incorporação no momento da tabela consultada. Book fonte traz aviso "material de uso interno, proibida a divulgação" — usamos aqui apenas dados factuais (specs, preços de tabela), não texto de marketing, para uso em ferramenta interna de inteligência competitiva. Bairro fora do cluster central (Três Figueiras).',
    fontes: ['tabela', 'memorial', 'web'],
  },
  {
    id: 'silent',
    nome: 'Silent',
    incorporadora: 'PlatzPar (constr. 4T Construtora)',
    bairro: 'Petrópolis',
    endereco: 'Rua Professor Langendonck, 275',
    dataLancamento: null,
    dataEntrega: null,
    dataEntregaObs: 'Entregue — "pronta para morar" na tabela de vendas (mar/2026)',
    totalUnidades: 25,
    unidadesEstoque: 14,
    tipologia: '3 suítes (+ garden)',
    metragem: '143,04 – 148,88 m² (garden 193,45 m²)',
    precoM2: 14411,
    precoAPartirOrulo: null,
    pavimentos: 14,
    aptosPorAndar: 2,
    projeto: 'Miguel Esnaola / Studio Prudêncio Arquitetura',
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Pleno (áreas condominiais e privativas)',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: false,
      quadraPoli: false, academia: true, saunaSeca: true, saunaUmida: false,
      salaMassagem: true, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Contrapiso e divisórias com isolamento acústico.',
    esquadrias: 'PVC com vidro duplo em todo o apartamento.',
    outros: 'Certificação Diamante; reaproveitamento de água de chuva; LED 100%; biometria/reconhecimento facial; estacionamento com pintura epóxi.',
    observacao: 'Mesma construtora (4T) do Casa Gardel — incorporadora só identificada via book, não confirmada em fonte externa. Já entregue e com quase metade do estoque original ainda disponível (44%), ritmo de venda mais lento da base.',
    fontes: ['tabela', 'memorial'],
  },
  {
    id: 'sonetto',
    nome: 'Sonetto',
    incorporadora: 'Woss',
    bairro: 'Menino Deus',
    endereco: 'Rua Itororó, 100',
    dataLancamento: null,
    dataLancamentoObs: 'marcado como "pré-venda" na tabela, sem data explícita',
    dataEntrega: null,
    totalUnidades: 62,
    totalUnidadesObs: 'ficha técnica do book diz 62; tabela de vendas (4 páginas) lista 61 linhas — possível unidade 1701 ausente/renumerada, não resolvido',
    unidadesEstoque: 55,
    tipologia: '3 suítes (+ garden)',
    metragem: '133,64 – 153,50 m² (garden 293,84 – 300,47 m²)',
    precoM2: 17080,
    precoAPartirOrulo: null,
    pavimentos: 19,
    aptosPorAndar: 4,
    projeto: 'Hype Studio Arquitetura',
    interiores: 'Hype Studio Arquitetura',
    paisagismo: 'Tellini Vontobel',
    luminotecnico: 'Studio Sandra Thomé',
    gerador: null,
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: true, academia: true, saunaSeca: false, saunaUmida: true,
      salaMassagem: true, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: false, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Concreto aparente; lajes onduladas; sacadas com floreiras integradas.',
    esquadrias: 'Piso-teto.',
    outros: 'Piscina no rooftop com raia de 12,5m + SPA; salão de festas de 122,62 m².',
    observacao: 'Bairro fora do cluster central (Menino Deus) — bem mais distante do Synthè, referência de preço/produto da mesma incorporadora (Woss) do Galeria Jardim e Marquês 650. Em pré-venda, apenas 11,3% vendido — o menos avançado da base.',
    fontes: ['tabela', 'memorial'],
  },
  {
    id: 'verissimo',
    nome: 'Veríssimo',
    incorporadora: 'Tomasetto Engenharia',
    bairro: 'Bela Vista',
    endereco: 'Rua Engenheiro Veríssimo de Matos, 151',
    dataLancamento: null,
    dataEntrega: '2028-10-30',
    totalUnidades: 16,
    unidadesEstoque: 7,
    tipologia: '3 suítes',
    metragem: '202,60 m² (1/andar) + cobertura duplex 405,02 m²',
    precoM2: 24180,
    precoAPartirOrulo: null,
    pavimentos: 22,
    aptosPorAndar: 1,
    projeto: 'Ideia1 Arquitetura',
    interiores: null,
    paisagismo: 'Tellini Vontobel',
    luminotecnico: null,
    gerador: 'Pleno (100%)',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: false,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: false, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Alvenaria convencional; laje com manta acústica + contrapiso.',
    esquadrias: 'Piso-teto.',
    outros: 'Guarita blindada; espera para automação residencial; piso aquecido nos 3 banheiros das suítes; piscina com raia de 20m, quebra-gelo, SPA e prainha; gerador atende 100% da carga.',
    observacao: 'Mesma incorporadora (Tomasetto) do Bordini 1595. Só 1 apto/andar em 22 pavimentos — maior verticalidade relativa da base, preço/m² é o 2º mais alto (atrás só do Bordini 1595).',
    fontes: ['tabela', 'memorial'],
  },
  {
    id: 'vista',
    nome: 'Vista',
    incorporadora: 'Stemmer Rodrigues',
    bairro: 'Bela Vista',
    endereco: 'Rua Engenheiro Adolfo Stern / Engenheiro Olavo Nunes',
    dataLancamento: null,
    dataEntrega: null,
    dataEntregaObs: 'Entregue — "pronta para morar" na tabela de vendas (mar/2026)',
    totalUnidades: 21,
    unidadesEstoque: 1,
    tipologia: '3 suítes',
    metragem: '163,45 – 164,78 m²',
    precoM2: 20497,
    precoAPartirOrulo: null,
    pavimentos: 15,
    aptosPorAndar: 2,
    projeto: 'Stemmer Rodrigues (Arq. Roberto Stemmer)',
    interiores: 'Ingrid Stemmer',
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Sim',
    amenidades: {
      salaoFestas: false, sGourmet: false, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Linguagem de concreto aparente ("cru, simples, bruto" — conceito do escritório).',
    esquadrias: 'Janelas panorâmicas com peitoril baixo; persianas motorizadas; vidros laminados de alto desempenho térmico/acústico; fechadura eletrônica.',
    outros: 'Lareira e churrasqueira em todas as plantas; brinquedoteca montessoriana.',
    observacao: 'Mesma incorporadora/arquiteto (Stemmer Rodrigues) do Voz. Entregue e praticamente esgotado (95,2% vendido, sobra 1 unidade) — sem salão de festas dedicado, incomum na base.',
    fontes: ['tabela', 'memorial'],
  },
  {
    id: 'voz',
    nome: 'Voz',
    incorporadora: 'Stemmer Rodrigues',
    bairro: 'Petrópolis',
    endereco: 'Rua Soledade, 223',
    dataLancamento: null,
    dataEntrega: null,
    dataEntregaObs: 'Entregue — "pronta para morar" na tabela de vendas (mar/2026)',
    totalUnidades: 23,
    unidadesEstoque: 1,
    tipologia: '3 suítes (+ garden e cobertura)',
    metragem: '160,02 m² (garden 181,20 m² · cobertura 320,04 m²)',
    precoM2: 20306,
    precoAPartirOrulo: null,
    pavimentos: 15,
    aptosPorAndar: 2,
    projeto: 'Stemmer Rodrigues',
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Pleno',
    amenidades: {
      salaoFestas: false, sGourmet: false, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: true, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Manta acústica em toda a unidade.',
    esquadrias: 'Vidros laminados de alto desempenho.',
    outros: 'Espaço Zen (diferencial não padrão na base); cercamento em vidro; depósitos individuais; lareira e churrasqueira.',
    observacao: 'Mesma incorporadora/arquiteto (Stemmer Rodrigues) do Vista, produto irmão do "Poema" (entregue em 2020). Entregue e praticamente esgotado (95,7% vendido).',
    fontes: ['tabela', 'memorial'],
  },
  {
    id: 'origo',
    nome: 'Órigo',
    incorporadora: 'Krystal',
    bairro: 'Auxiliadora',
    endereco: 'Rua Felipe Neri, 149 (esquina Av. Mariland)',
    dataLancamento: null,
    dataEntrega: null,
    totalUnidades: 28,
    totalUnidadesObs: '+ 2 lojas térreas',
    unidadesEstoque: 18,
    tipologia: '3 suítes (1 master + 2 americanas)',
    metragem: '131 – 142 m² (garden 172 m² · cobertura duplex 270 m²)',
    precoM2: 17382,
    precoAPartirOrulo: null,
    pavimentos: 17,
    aptosPorAndar: 2,
    projeto: 'Studio Ronaldo Rezende',
    interiores: 'Tellini Vontobel Arquitetura',
    paisagismo: 'Tellini Vontobel Arquitetura',
    luminotecnico: 'Studio FOS',
    gerador: 'Pleno (100% privativas + condominiais)',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: true, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: false, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Fachada em pastilha + porcelanato ventilado.',
    esquadrias: 'Não detalhado além do padrão de fachada.',
    outros: 'Certificação Diamante; estacionamento com pintura epóxi; infra para carregador elétrico (1/unidade); LED 100%; reaproveitamento de água de chuva; paisagismo com espécies nativas e horta.',
    observacao: 'Mesmo projetista (Studio Ronaldo Rezende) do Bordini 1595 e Galeria Jardim, e mesmo escritório de interiores/paisagismo (Tellini Vontobel) do Bordini 1595, Marquês 650 e Galeria Jardim.',
    fontes: ['tabela', 'memorial'],
  },
]

export const DEVELOPMENTS = raw.map((d) => {
  const vendidas = d.totalUnidades != null ? d.totalUnidades - d.unidadesEstoque : null
  return {
    ...d,
    unidadesVendidas: vendidas,
    pctVendido: vendidas != null ? +(100 * vendidas / d.totalUnidades).toFixed(1) : null,
    amenidadesCount: amenCount(d.amenidades),
  }
})

export const SYNTHE = DEVELOPMENTS.find((d) => d.isSynthe)
export const COMPETITORS = DEVELOPMENTS.filter((d) => !d.isSynthe)

export const DEPTH_LABEL = {
  completo: 'Memorial completo',
  parcial: 'Specs parciais',
  nenhum: 'Sem specs',
}

export function fmtMoney(v) {
  if (v == null) return '—'
  return 'R$ ' + Math.round(v).toLocaleString('pt-BR')
}

export function fmtPct(v) {
  if (v == null) return '—'
  return v.toLocaleString('pt-BR', { minimumFractionDigits: 1, maximumFractionDigits: 1 }) + '%'
}

export function fmtDate(iso) {
  if (!iso) return 'não informado'
  const [y, m, d] = iso.split('-')
  return `${d}/${m}/${y}`
}

export const LAST_UPDATED = '26 de agosto de 2026'
