// Base real do estudo de concorrência do Synthè (Plaenge · TGD, Mont'Serrat,
// Porto Alegre). Nenhum dado aqui é fictício — vem da pasta de pesquisa
// "concorrentes synthe" (tabelas de vendas, memoriais descritivos, books),
// do Órulo (consulta autenticada em 25/ago/2026) e de checagem cruzada com
// Rial Imóveis + sites institucionais das incorporadoras.
//
// Ver SOURCES para a legenda de cada chave usada em `fontes`.

export const SOURCES = {
  tabela: {
    label: 'Tabela de vendas oficial',
    detalhe: 'Preço/m² por unidade em estoque, mar/2026 (concorrentes) e ago/2026 (Synthè)',
  },
  orulo: {
    label: 'Órulo',
    detalhe: 'Plataforma paga, sessão autenticada — estoque, lançamento/entrega, áreas comuns, preço "a partir". Consultado em 25/ago/2026',
  },
  rial: {
    label: 'Rial Imóveis',
    detalhe: '211 anúncios ativos na região cruzados por preço/m² — validação independente, 25/ago/2026',
  },
  memorial: {
    label: 'Memorial / ficha técnica / book',
    detalhe: 'PDFs oficiais das incorporadoras — estrutura, fachada, esquadrias, equipe de projeto',
  },
  web: {
    label: 'Site institucional / busca dirigida',
    detalhe: 'Sites das incorporadoras e portais (Bridge, Colnaghi, Foxter, Auxiliadora Predial, Urban) — confirmação cruzada de incorporadora, datas e resolução de divergências',
  },
}

const AMENITY_KEYS = [
  ['salaoFestas', 'Salão de festas'],
  ['sGourmet', 'Espaço gourmet'],
  ['brinquedoteca', 'Brinquedoteca'],
  ['playground', 'Playground'],
  ['quadraPoli', 'Quadra poliesportiva'],
  ['academia', 'Academia'],
  ['saunaSeca', 'Sauna seca'],
  ['saunaUmida', 'Sauna úmida'],
  ['salaMassagem', 'Sala de massagem'],
  ['piscinaInterna', 'Piscina interna'],
  ['piscinaExterna', 'Piscina externa'],
  ['espacoPet', 'Espaço pet'],
  ['bicicletario', 'Bicicletário'],
  ['quadraTenis', 'Quadra de tênis'],
  ['quadraBeachTenis', 'Quadra de beach tênis'],
]
export { AMENITY_KEYS }

function amenCount(amen) {
  return AMENITY_KEYS.reduce((n, [k]) => n + (amen[k] === true ? 1 : 0), 0)
}

const raw = [
  {
    id: 'synthe',
    isSynthe: true,
    nome: 'Synthè',
    incorporadora: 'Plaenge · TGD',
    bairro: "Mont'Serrat",
    endereco: 'Rua Pedro Ivo, 550',
    dataLancamento: '2026-03-20',
    dataLancamentoObs: 'confirmado — registro de incorporação',
    dataEntrega: null,
    totalUnidades: 32,
    unidadesEstoque: 19,
    tipologia: '3 suítes',
    metragem: '176,80 – 180,39 m² (tipo) · 295,99 m² (penthouse)',
    precoM2: 18507,
    precoAPartirOrulo: null,
    pavimentos: 18,
    aptosPorAndar: 2,
    projeto: 'Baldasso Arquitetura e Engenharia',
    interiores: 'Maena Design Conecta',
    paisagismo: 'Creare Paisagismo',
    luminotecnico: null,
    gerador: 'Pleno',
    amenidades: {
      salaoFestas: true, sGourmet: 'parcial', brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: null, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'nenhum',
    estrutura: 'Sacadas onduladas com floreiras integradas à fachada; volume da torre em tom escuro, base com brise ripado em madeira. Estrutura não detalhada — sem memorial descritivo disponível.',
    esquadrias: 'Não detalhado no book disponível (sem memorial descritivo).',
    outros: 'Gerador pleno; espera para carregador elétrico; hall privativo por andar; halls sociais em mármore e madeira.',
    observacao: 'Único da base sem memorial descritivo público — os diferenciais citados no book (gerador pleno, espera p/ carregador elétrico) já são padrão em 8 dos 11 concorrentes.',
    fontes: ['tabela', 'memorial'],
  },
  {
    id: 'uba',
    nome: 'Ubá',
    incorporadora: 'Zuckhan',
    bairro: 'Bela Vista',
    endereco: 'Rua Barão de Ubá, 690',
    dataLancamento: '2025-09-01',
    dataEntrega: '2028-09-30',
    totalUnidades: 32,
    unidadesEstoque: 17,
    tipologia: '3 suítes',
    metragem: '178 – 331 m²',
    precoM2: 18551,
    precoAPartirOrulo: 4165730,
    pavimentos: 19,
    aptosPorAndar: 2,
    projeto: 'Torres Arquiteto',
    interiores: 'Arquitetura Nacional',
    paisagismo: 'Recanto Paisagismo',
    luminotecnico: 'Cristina Maluf',
    gerador: '100%',
    amenidades: {
      salaoFestas: true, sGourmet: false, brinquedoteca: true, playground: true,
      quadraPoli: true, academia: true, saunaSeca: true, saunaUmida: false,
      salaMassagem: true, piscinaInterna: true, piscinaExterna: true,
      espacoPet: false, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Fachada em painel arquitetônico premium.',
    esquadrias: 'Esquadrias piso-teto com vidro duplo.',
    outros: 'Segurança com biometria/reconhecimento facial; automação residencial (iluminação, som, cortinas); adega climatizada privativa por apto; elevador panorâmico; pé-direito de 3m.',
    observacao: 'Corrigido nesta pesquisa: incorporadora é Zuckhan, não Woss (base de março) — confirmado por 3 fontes independentes (Órulo, site oficial da Zuckhan, portais).',
    fontes: ['tabela', 'orulo', 'memorial', 'web'],
  },
  {
    id: 'bordini',
    nome: 'Bordini 1595',
    incorporadora: 'Tomasetto',
    bairro: 'Bela Vista',
    endereco: 'Rua Coronel Bordini, 1595',
    dataLancamento: '2024-04-01',
    dataEntrega: '2027-04-30',
    totalUnidades: 23,
    unidadesEstoque: 3,
    tipologia: '3 suítes',
    metragem: '154 – 198 m² (+ 2 coberturas duplex)',
    precoM2: 24666,
    precoAPartirOrulo: 2868900,
    pavimentos: 14,
    aptosPorAndar: 2,
    projeto: 'Ronaldo Rezende',
    interiores: null,
    paisagismo: 'Tellini Vontobel',
    luminotecnico: null,
    gerador: 'Full',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: true, saunaUmida: false,
      salaMassagem: true, piscinaInterna: true, piscinaExterna: false,
      espacoPet: false, bicicletario: false, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'nenhum',
    estrutura: 'Não informado — sem memorial descritivo disponível, apenas book institucional.',
    esquadrias: 'Não informado.',
    outros: 'Fitness de 86m² assinado por Lucas Pretto (Pretto Treinamento).',
    observacao: 'Maior velocidade de venda da base (87%) mesmo sendo o mais caro por m² — marca/produto pesam mais que preço aqui.',
    fontes: ['tabela', 'orulo', 'rial'],
  },
  {
    id: 'artur-rocha',
    nome: 'Artur Rocha 1133',
    incorporadora: 'AB Incorporadora',
    bairro: 'Bela Vista',
    endereco: 'Rua Artur Rocha, 1133',
    dataLancamento: '2023-11-01',
    dataEntrega: '2027-11-30',
    totalUnidades: 10,
    unidadesEstoque: 6,
    tipologia: '3 suítes',
    metragem: '180 – 229 m² (garden)',
    precoM2: 22012,
    precoAPartirOrulo: 4990000,
    pavimentos: 12,
    aptosPorAndar: 1,
    projeto: 'Hype Studio',
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Full',
    amenidades: {
      salaoFestas: true, sGourmet: false, brinquedoteca: false, playground: false,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: false,
      espacoPet: false, bicicletario: false, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Não informado.',
    esquadrias: 'Esquadrias piso-teto.',
    outros: 'Espera p/ carregador elétrico (1/apto); isolamento acústico nas tubulações; manta acústica entre laje e contrapiso; persiana motorizada.',
    observacao: 'Preço/m² (R$22.011 no Órulo) bate quase exato com nosso cálculo próprio (R$22.012) — boa validação cruzada.',
    fontes: ['tabela', 'orulo', 'memorial', 'web'],
  },
  {
    id: 'galeria-jardim',
    nome: 'Galeria Jardim',
    incorporadora: 'Woss',
    bairro: "Mont'Serrat",
    endereco: 'Rua Silva Jardim, 600',
    dataLancamento: '2026-05-07',
    dataEntrega: '2029-07-31',
    totalUnidades: 54,
    unidadesEstoque: 28,
    tipologia: '3 suítes',
    metragem: '154,62 – 352,20 m² (tipo, garden e cobertura)',
    precoM2: null,
    precoAPartirOrulo: 2172287,
    pavimentos: 18,
    aptosPorAndar: 4,
    projeto: 'Studio Ronaldo Rezende',
    interiores: 'Vitá Arquitetos',
    paisagismo: 'Tellini Vontobel',
    luminotecnico: 'Studio Sandra Thomé',
    gerador: 'Full',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: true, academia: true, saunaSeca: true, saunaUmida: true,
      salaMassagem: true, piscinaInterna: true, piscinaExterna: true,
      espacoPet: true, bicicletario: true, quadraTenis: false, quadraBeachTenis: true,
    },
    profundidade: 'completo',
    estrutura: 'Altura de pavimento 3,05m; laje + manta acústica de alto desempenho + contrapiso, piso com 19 a 24cm — atenuação acústica.',
    esquadrias: 'Esquadrias piso-teto com peitoril em vidro; alumínio anodizado de alto desempenho; vidros laminados termoacústicos; persianas motorizadas nas suítes.',
    outros: 'Água quente individual; churrasqueira c/ exaustão mecânica; lareira a lenha; espera adega (projeto Lacava); guarita com vidros multilaminados.',
    observacao: 'Divergência resolvida: ficha técnica oficial confirma 54 unidades (não 72, número que nunca existiu de fato nas fontes — era artefato de busca). Vendeu 26 das 54 desde o lançamento em mai/2026.',
    fontes: ['orulo', 'memorial', 'web'],
  },
  {
    id: 'marques-650',
    nome: 'Marquês 650',
    incorporadora: 'Woss',
    bairro: 'Moinhos de Vento',
    endereco: 'Rua Marquês do Herval, 650',
    dataLancamento: '2025-05-30',
    dataEntrega: '2028-03-30',
    totalUnidades: 47,
    unidadesEstoque: 29,
    tipologia: '3 e 4 suítes',
    metragem: '143,76 – 330,43 m² (incl. coberturas duplex)',
    precoM2: 18810,
    precoAPartirOrulo: 2552400,
    pavimentos: 15,
    aptosPorAndar: 4,
    projeto: 'OPSA (+ restauração: arq. Evandro Eifler Jr.)',
    interiores: 'OPSA',
    paisagismo: 'Tellini Vontobel',
    luminotecnico: 'OPSA',
    gerador: 'Full',
    amenidades: {
      salaoFestas: true, sGourmet: false, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: true,
      salaMassagem: true, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Restauração de prédio histórico (Patrimônio Histórico, arq. Evandro Eifler Jr.); abas e sacadas em concreto aparente — sombreamento + compartimentação de incêndio.',
    esquadrias: 'Esquadrias piso-teto com trilhos embutidos; alumínio anodizado de alto desempenho; vidros laminados termoacústicos; persianas motorizadas.',
    outros: 'Pisos em Pedra Portuguesa; revestimentos nobres (mármore Donatello e amadeirados); piscina raia 25m; Selo Diamante de Sustentabilidade.',
    observacao: 'Único projeto de restauração de prédio histórico da base — história impossível de replicar pelos concorrentes.',
    fontes: ['tabela', 'orulo', 'memorial', 'web'],
  },
  {
    id: 'nuances',
    nome: 'Nuances',
    incorporadora: 'Ivo Rizzo',
    bairro: 'Moinhos de Vento',
    endereco: 'Rua Coronel Bordini, 668',
    dataLancamento: '2025-08-27',
    dataEntrega: '2028-12-31',
    totalUnidades: 17,
    unidadesEstoque: 13,
    tipologia: '3 suítes',
    metragem: '154 – 326 m² (4 tipologias, incl. cobertura)',
    precoM2: 19521,
    precoAPartirOrulo: 3025265,
    pavimentos: 12,
    aptosPorAndar: 2,
    projeto: 'Smart Arquitetura (desenv.: Cimo Arquitetura)',
    interiores: 'Ar Arquitetura',
    paisagismo: 'Daniel Dillenburg',
    luminotecnico: null,
    gerador: 'Sim',
    amenidades: {
      salaoFestas: true, sGourmet: false, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: false, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Concreto armado convencional; alvenaria em bloco cerâmico 19cm com isolamento acústico; fachada em revestimento cerâmico Eliane (Chelsea Powder Mesh) + amadeirado HPL/ACM; peitoris em basalto polido.',
    esquadrias: 'Alumínio c/ pintura eletrostática branca ou PVC branco, vidro laminado; vidro duplo insulado nos dormitórios; persianas motorizadas.',
    outros: 'Toldos de fachada motorizados; Selo Diamante de Sustentabilidade.',
    observacao: null,
    fontes: ['tabela', 'orulo', 'memorial', 'web'],
  },
  {
    id: 'legacy',
    nome: 'Legacy · Porsche Consulting',
    incorporadora: 'Cyrela Goldsztein',
    bairro: 'Moinhos de Vento',
    endereco: 'Rua Dr. Florêncio Ygartua, 415',
    dataLancamento: '2025-08-06',
    dataEntrega: '2028-10-31',
    totalUnidades: 48,
    unidadesEstoque: 18,
    tipologia: '3 e 4 suítes',
    metragem: '168 – 393 m² (incl. coberturas duplex)',
    precoM2: 20798,
    precoAPartirOrulo: 3529292,
    pavimentos: 16,
    aptosPorAndar: 4,
    projeto: 'Hype Studio',
    interiores: 'Cassia Kroeff',
    paisagismo: 'Creare',
    luminotecnico: null,
    gerador: 'N/S',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: true, academia: true, saunaSeca: true, saunaUmida: null,
      salaMassagem: null, piscinaInterna: true, piscinaExterna: true,
      espacoPet: true, bicicletario: true, quadraTenis: true, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Torre de 16 pavimentos, 48 aptos (4/andar); paredes em alvenaria; fachadas em revestimento texturizado e/ou pintura — sem revestimento nobre/pétreo.',
    esquadrias: 'Alumínio com guarnições em alumínio, acabamento em pintura (padrão Cyrela); não entregues em ambientes de serviço.',
    outros: '3 elevadores (2 sociais + 1 serviço), marca Atlas.',
    observacao: 'Apesar da marca "Porsche Consulting", a especificação de fachada é mais simples que a de outros concorrentes do mesmo padrão de preço.',
    fontes: ['tabela', 'orulo', 'memorial', 'web'],
  },
  {
    id: 'anita-green',
    nome: 'Anita Green',
    incorporadora: 'Joal Teitelbaum',
    bairro: "Mont'Serrat",
    endereco: 'Rua Anita Garibaldi, 51',
    dataLancamento: '2021-04-01',
    dataEntrega: '2025-09-30',
    totalUnidades: 37,
    unidadesEstoque: 8,
    tipologia: '3 suítes (+ 2 dorm. e garden)',
    metragem: '155,76 – 192,60 m² (+ 75,68 m² e garden 361,54 m²)',
    precoM2: 19865,
    precoAPartirOrulo: 3604355,
    pavimentos: 16,
    aptosPorAndar: 2,
    projeto: 'Ideia1 Arquitetura',
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Sim',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: true, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: null, bicicletario: null, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Fachadas em painel arquitetônico.',
    esquadrias: 'Vidros duplos nos dormitórios.',
    outros: 'Iluminação automatizada nos apartamentos; gerador conforme carga definida em projeto.',
    observacao: 'Corrigido nesta pesquisa: total real é 37 unidades (não 24 — a tabela de março só listava o que ainda estava à venda). Único concorrente no mesmo bairro do Synthè com preço de tabela ativo.',
    fontes: ['tabela', 'orulo', 'rial', 'memorial'],
  },
  {
    id: 'matiz-moinhos',
    nome: 'Matiz Moinhos',
    incorporadora: 'Zuckhan',
    bairro: 'Auxiliadora',
    endereco: 'Rua Coronel Bordini, 1024',
    dataLancamento: '2024-10-17',
    dataEntrega: '2029-09-30',
    totalUnidades: 28,
    unidadesEstoque: 19,
    tipologia: '3 suítes',
    metragem: '153 – 254 m² (incl. garden e cobertura)',
    precoM2: 18276,
    precoAPartirOrulo: 2567158,
    pavimentos: 17,
    aptosPorAndar: 2,
    projeto: 'Não identificado (só logo no material)',
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: '100%',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: true,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: null, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Concreto aparente tratado; plaquetas cerâmicas na fachada.',
    esquadrias: 'Alumínio com pintura eletrostática e vidros laminados.',
    outros: 'Certificação de Sustentabilidade Ambiental Diamante; LED 100% nas áreas condominiais; infra p/ carregador elétrico; guarita com vidros blindados.',
    observacao: 'Data de entrega divergia entre portais (out/2027 a set/2028) — resolvido com a data oficial do Órulo (set/2029).',
    fontes: ['tabela', 'orulo', 'memorial'],
  },
  {
    id: 'aura',
    nome: 'Aura',
    incorporadora: 'Frass',
    bairro: 'Bela Vista',
    endereco: 'Rua Coronel Bordini, 1644',
    dataLancamento: '2021-11-01',
    dataEntrega: '2025-03-30',
    totalUnidades: 23,
    unidadesEstoque: 3,
    tipologia: '3 suítes',
    metragem: '160,52 – 187,62 m² (garden 288,90 m²)',
    precoM2: 21073,
    precoAPartirOrulo: 3659369,
    pavimentos: 13,
    aptosPorAndar: 2,
    projeto: 'André Petracco Arquitetura e Smart',
    interiores: 'Ambidestro Arquitetura',
    paisagismo: 'Krebs+ Paisagismo',
    luminotecnico: 'Stúdio FOS Iluminação',
    gerador: 'Sim',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: false,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: null, bicicletario: null, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'completo',
    estrutura: 'Concreto armado convencional; alvenaria em bloco cerâmico; fachada em concreto aparente e porcelanato imitando madeira; brises em alumínio e ACM pintado no térreo.',
    esquadrias: 'PVC ou alumínio c/ pintura eletrostática cor chumbo, vidro laminado; esquadrias internas em madeira maciça branca; persianas automatizadas nas suítes.',
    outros: 'Piscina com pastilhas NGK/Atlas; adega condominial climatizada (Lacava).',
    observacao: 'Entregue desde mar/2025 — "Pronto novo". Empata com Bordini 1595 como o mais vendido da base (87%).',
    fontes: ['tabela', 'orulo', 'rial', 'memorial'],
  },
  {
    id: 'casa-gardel',
    nome: 'Casa Gardel',
    incorporadora: 'PlatzPar (constr. 4T Construtora)',
    bairro: 'Bela Vista',
    endereco: 'Rua Carlos Gardel, 210',
    dataLancamento: '2026-03-01',
    dataEntrega: '2029-03-31',
    totalUnidades: 13,
    unidadesEstoque: 9,
    tipologia: '3 suítes (+ garden e andar inteiro)',
    metragem: '117 – 255 m² (garden 173,28 m²)',
    precoM2: 18042,
    precoAPartirOrulo: 2001757,
    pavimentos: 10,
    aptosPorAndar: 2,
    projeto: 'Não identificado no material',
    interiores: null,
    paisagismo: null,
    luminotecnico: null,
    gerador: 'Pleno',
    amenidades: {
      salaoFestas: true, sGourmet: true, brinquedoteca: true, playground: true,
      quadraPoli: false, academia: true, saunaSeca: false, saunaUmida: false,
      salaMassagem: false, piscinaInterna: false, piscinaExterna: true,
      espacoPet: null, bicicletario: true, quadraTenis: false, quadraBeachTenis: false,
    },
    profundidade: 'parcial',
    estrutura: 'Torre única em concreto aparente (design autoral valoriza biofilia + concreto aparente).',
    esquadrias: 'Vidros duplos em todos os apartamentos.',
    outros: 'Churrasqueira em todos os apartamentos; estacionamento com pintura epóxi; certificado de Sustentabilidade Ambiental (redução de IPTU).',
    observacao: 'Incorporadora só identificada via busca web (PlatzPar) — não aparece nos PDFs de vendas.',
    fontes: ['tabela', 'orulo', 'web'],
  },
]

export const DEVELOPMENTS = raw.map((d) => {
  const vendidas = d.totalUnidades - d.unidadesEstoque
  return {
    ...d,
    unidadesVendidas: vendidas,
    pctVendido: +(100 * vendidas / d.totalUnidades).toFixed(1),
    amenidadesCount: amenCount(d.amenidades),
  }
})

export const SYNTHE = DEVELOPMENTS.find((d) => d.isSynthe)
export const COMPETITORS = DEVELOPMENTS.filter((d) => !d.isSynthe)

export const DEPTH_LABEL = {
  completo: 'Memorial completo',
  parcial: 'Specs parciais',
  nenhum: 'Sem specs',
}

export function fmtMoney(v) {
  if (v == null) return '—'
  return 'R$ ' + Math.round(v).toLocaleString('pt-BR')
}

export function fmtPct(v) {
  if (v == null) return '—'
  return v.toLocaleString('pt-BR', { minimumFractionDigits: 1, maximumFractionDigits: 1 }) + '%'
}

export function fmtDate(iso) {
  if (!iso) return 'não informado'
  const [y, m, d] = iso.split('-')
  return `${d}/${m}/${y}`
}

export const LAST_UPDATED = '25 de agosto de 2026'
